[project]
name = "beancount-bot"
version = "0.1.0"
description = "Another Telegram bot."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beancount>=3.0.0",
    "beanquery>=0.1.dev0",
    "python-dotenv>=1.0.1",
    "python-telegram-bot[job-queue]>=21.5",
    "pyyaml>=6.0",
]
