queries:
  pay:
    description: |
      Monthly outgoing totals for matching accounts in 2025.
    query: |
      select account, month(date) as month, sum(position)
      from year=2025
      where account ~ [args] and number < 0
      group by account, month
      order by month desc
